bases:
- ../base
resources:
- hostpath-storage-class.yaml
patchesStrategicMerge:
- ingress-routes.yaml
namespace: clud
configMapGenerator:
- name: clud-server-config
  literals:    
  - basehostname=clud.ghyston.com
generatorOptions:
  disableNameSuffixHash: true